version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:9.10

    working_directory: ~/my-project

    setps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: 'yarn install'

      - run:
          name: ESLint
          command: 'yarn lint'

  build:
    docker:
      - image: circleci/node:9.10
        ENVIRONMENT:
          BUILD_ENVIRONMENT: production

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: sudo apt-get update && sudo apt-get install -y awscli


      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Building
          command: 'yarn build'

  deploy-production:
    requires:
        - build
    branches:
      only: master
    docker:
        - image: circleci/node:9.10
    working_directory: ~/repo
    steps:
      - attach_workspace:
         at: ~/repo
      - run:
          name: Deploy
          command: 'aws s3 sync public/ s3://brianbancroft.io --delete'

workflows:
  version: 2
  build-deploy:
    jobs:
      - lint
      - build:
        requires:
          - lint
        filters:
          branches:
            only: master
      - deploy-production:
          requires:
            - lint
            - build
          filters:
            branches:
              only: master